trigger:
 - master

pool:
 name: Default

steps:
 - script: echo Hello, its My Simple Calculator App
   displayName: 'Run an echo command'
 - script: mvn clean install
   displayName: 'Build with maven'
 - script: java -jar target/SimpleCalci-0.0.1-SNAPSHOT.jar
   displayName: 'Run a jar file of My Simple Calculator App'
